#!/usr/bin/env bash
# shellcheck shell=bash

# These defaults were set for a specific cluster configuration.
# You MUST override these values to match your own cluster before using this mode.
# In particular, SLURM_ATTACHED_REMOTE_PARTITIONS and SLURM_ATTACHED_REMOTE_QOS
# are cluster-specific. Set them in your shell before calling the launcher script,
# or edit this file directly.

: "${SLURM_ATTACHED_REMOTE_PARTITIONS:=array}"
: "${SLURM_ATTACHED_REMOTE_QOS:=array_qos}"
: "${SLURM_ATTACHED_REMOTE_TIME:=00:20:00}"
: "${SLURM_ATTACHED_REMOTE_MEM_PER_TASK:=2G}"
: "${SLURM_ATTACHED_CPUS_PER_EVAL:=1}"
: "${SLURM_ATTACHED_REMOTE_WORKERS_PER_TASK:=1}"
: "${SLURM_ATTACHED_REMOTE_PARALLEL_EVALS_PER_TASK:=0}"
: "${SLURM_ATTACHED_REMOTE_MAX_ARRAY_TASKS:=512}"
: "${SLURM_ATTACHED_LOCAL_CPUS:=$(nproc)}"
_MAX_LOCAL_SLOTS=$(( SLURM_ATTACHED_LOCAL_CPUS / SLURM_ATTACHED_CPUS_PER_EVAL ))
if [[ -n "${CURIO_EVALUATOR_NUM_WORKERS:-}" ]] && (( CURIO_EVALUATOR_NUM_WORKERS < _MAX_LOCAL_SLOTS )); then
	_MAX_LOCAL_SLOTS="$CURIO_EVALUATOR_NUM_WORKERS"
fi
: "${SLURM_ATTACHED_LOCAL_INITIAL_SHARDS:=$_MAX_LOCAL_SLOTS}"
: "${SLURM_ATTACHED_LOCAL_PARALLEL_JOBS:=$_MAX_LOCAL_SLOTS}"
: "${SLURM_ATTACHED_EVAL_SHARD_SIZE:=1}"

if [[ "${SLURM_ATTACHED_REMOTE_PARTITIONS}" == "cpu,array" ]]; then
	SLURM_ATTACHED_REMOTE_PARTITIONS="array"
fi

export SLURM_ATTACHED_REMOTE_PARTITIONS
export SLURM_ATTACHED_REMOTE_QOS
export SLURM_ATTACHED_REMOTE_TIME
export SLURM_ATTACHED_REMOTE_MEM_PER_TASK
export SLURM_ATTACHED_CPUS_PER_EVAL
export SLURM_ATTACHED_REMOTE_WORKERS_PER_TASK
export SLURM_ATTACHED_REMOTE_PARALLEL_EVALS_PER_TASK
export SLURM_ATTACHED_REMOTE_MAX_ARRAY_TASKS
export SLURM_ATTACHED_LOCAL_CPUS
export SLURM_ATTACHED_LOCAL_INITIAL_SHARDS
export SLURM_ATTACHED_LOCAL_PARALLEL_JOBS
export SLURM_ATTACHED_EVAL_SHARD_SIZE
